### ISSUE TITLE
Cursor gets stuck as `|` when using text objects

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#331]
In the video below, I'm inside a `{ }` block.  I hit `vi{` to go into visual mode, select inner text object, bounded by `{ }`'.  After that, my cursor becomes `|` and remains like that as I hit `h` and `l`.  I then hit `<Esc>` to exit visual mode and the cursor stays a `|`.  For whatever reason, I then hit `<Space>` and the normal cursor shape comes back.

![cursor](https://cloud.githubusercontent.com/assets/817509/24478406/edeb1040-1497-11e7-8d10-b0458417d85c.gif)

Also, note that the mode `-- VISUAL --` disappears when I hit the `{` key even though I'm still in visual mode.

**Comment by extr0py** [comment]
Ah, interesting - I noticed this too intermittently but wasn't able to isolate a repro. It's great that you caught it in action 👍 

I'm wondering if there is some behavior / event timing difference in the latest Neovim. I didn't notice this until I updated the windows binaries. Or maybe there is a new value that comes from the `mode_change` event from the `msgpack-rpc` interface. It'd be helpful to audit the `mode_change` events  we get in `NeovimInstance`:
```
            } else if (command === "mode_change") {
                const newMode = a[0][0]
                this.emit("action", Actions.changeMode(newMode))
                this.emit("mode-change", newMode)
                ...
```

**Comment by keforbes** [comment]
I'll dig a bit deeper but here's the current behavior:

When I hit `v`, I see `-- VISUAL --` in Oni but no `mode_change` event fires.  I then hit `i` (nothing happens) then `{` and suddenly I get a `mode_change` event for `cmdline` and the cursor is stuck in `|`.  When I hit `<Space>`, I get a `mode_change` for `cmdline` followed by `normal` followed by `cmdline` followed by `normal`.  `normal` is the last `mode_change` so the cursor goes back to a normal mode block.

**Comment by keforbes** [comment]
Another update.  When I hit `{` and get the first `mode_change` for `cmdline`, the msgpack object actually has 15 entries of `normal` and 1 entry of `cmdline` which happens to be at `a[0][0]`.  The code is only expecting to find an entry at `a[0][0]` so we set our new mode to `cmdline`.

![mode_change](https://cloud.githubusercontent.com/assets/817509/24522006/617e1fa8-154b-11e7-90ae-ad4870f91cf6.png)

I'm not sure how Oni is supposed to handle this object but for this specific scenario, ignoring it would've been the best choice.

When I hit `<Space>` after being in this state and get `cmdline`, `normal`, `cmdline`, `normal` they're each `mode_change` events with a single entry at `a[0][0]`.  So at least those events are following our expected format, though I don't know why Neovim is firing them back-to-back like that.

Also, the reason for this issue in Oni is because `Cursor.tsx` sets itself to `|` anytime the `mode !== 'normal'` so `cmdline` comes in and we go to `|`.  I was tempted to fix this by just changing that logic to `mode === 'insert'` but Neovim actually behaves differently from Vim in this case.  In Vim, if I go to `cmdline` mode (`:`) the cursor remains as a block.  In Neovim, if I go to `cmdline` mode the cursor goes to `|`.  So Oni changing the cursor to `|` when it sees `cmdline` is the correct behavior (for Neovim), I just don't know why the event fires when I do `vi{`.

**Comment by keforbes** [comment]
I wonder if Oni is actually running some requests under the hood which are modifying the mode.  I'm seeing things like:
https://github.com/neovim/neovim/issues/5685
https://github.com/neovim/neovim/issues/6166
which are probably the real root cause for the madness I'm trying to code around.

**Comment by extr0py** [comment]
Nice find here! I would imagine those issues you linked are responsible. We may want some additional logging to see the sort of requests we are making to Neovim via msgpack-rpc. It's possible that there are some cases where we are making queries in the background, and that is interrupting the command sequence. 

For the cursor case in particular, we might be able to handle that by handling that array of items, instead of dropping the other ones.

I've seen some cases where I'd run a command like `dt(` and it would just be a no-op. That jives with the issue you linked - where perhaps that command sequence is being interrupted. It's never able to be reproduced, but maybe some additional logging could help when we do hit this. It's really helpful to know that executing those commands causes problems if hit in the middle of an input sequence.

**Comment by FrigoEU** [comment]
I'm unsure if this is related, but I'm getting one really annoying behavior. When I just type :vsplit + Enter, I make a vsplit, move to it, everything's good. However I have a keybinding (<leader>v) that does the exact same thing but silently

```
nnoremap <silent> <leader>v :vsplit<CR>
```

The split opens, my cursor moves there, but also it looks like it's in insert mode but I actually can't insert and am in this weird limbo until I eg. go actually into insert mode and go back out. The silent thing definitely has something to do with it, because without it it works fine. Also in terminal neovim (NVIM v0.2.0-1175-g210b013) this also works (the silent variation). It doesn't bother me so much anymore now since I know that it's because of <silent>, but I thought I'd let you know.

**Comment by keforbes** [comment]
Using the latest build of Oni and Neovim, I'm not seeing this issue anymore.  I'm guessing it was fixed in Neovim and we're probably just receiving the correct mode change events now.

**Comment by extr0py** [comment]
I'm actually still seeing this on occasion, so re-opening. It's annoying when it does happen, because it looks like we're in insert mode!
