### ISSUE TITLE
MYVIMRC not set?

### ISSUE THREAD

**Issue by am2605** [extr0py/oni#332]
Not sure if this is another Windows issue or not.  

If I select File->Preferences -> Edit Neovim Config, it loads an empty file.  If I enter some text there and save it, it creates a file named $MYVIMRC in the directory I launched the app from.

Am I supposed to set this myself, or should oni be giving it a value?

**Comment by keforbes** [comment]
I've seen the same issue but couldn't reproduce it.  When you opened the file it tried opening `$MYVIMRC` rather than expanding that to `init.vim`.  Saving the file then wrote out that incorrect name.

I saw the problem once but then when I selected the menu item again it opened the file correctly.  I'm not sure what steps are needed to reproduce.

**Comment by keforbes** [comment]
When you select `Edit Neovim Config`, check to see if it says `$MYVIMRC [new file]`

**Comment by am2605** [comment]
Yes, I can confirm it says `$MYVIMRC [new file]`

**Comment by extr0py** [comment]
Strange - I wonder what we are sending over in `browser\src\index.tsx`:
```
    ipcRenderer.on("menu-item-click", (_evt, message: string) => {
        if (message.startsWith(":")) {
            instance.command("exec \"" + message + "\"")
        } else {
            instance.command("exec \":normal! " + message + "\"")
        }
    })
```

Also, if you start `Oni`, and then type `:e $MYVIMRC`, do you get a different result? I'm wondering if there is some difference in terms of how we are opening it up

**Comment by extr0py** [comment]
Weird, I was able to  reproduce this on my Linux box but not on my Windows box. And if I run `nvim` from terminal, I get the same issue - so this might be an issue with neovim itself as opposed to Oni.

**Comment by keforbes** [comment]
> Strange - I wonder what we are sending over in browser\src\index.tsx:

Maybe I'm misunderstanding your comment, but `$MYVIMRC` is coming from `Commands.ts`
```
new CallbackCommand("oni.config.openInitVim", "Edit Neovim Config", "Edit configuration file ('init.vim') for Neovim", () => neovimInstance.open("$MYVIMRC")),
```

**Comment by keforbes** [comment]
For what it's worth, I see this issue on my Ubuntu system but not my Arch system. :man_shrugging:

**Comment by am2605** [comment]
> Also, if you start Oni, and then type :e $MYVIMRC, do you get a different result?

I am getting the same result.  

`:echo $MYVIMRC` is blank, it seems to me like the variable does not get set at all.

**Comment by am2605** [comment]
> And if I run nvim from terminal, I get the same issue - so this might be an issue with neovim itself as opposed to Oni.

If I launch nvim-qt.exe from oni\bin\x86\Neovim\bin, `:echo $MYVIMRC` gives me `~\AppData\Local\nvim\init.vim` which is what I would expect.

I wonder if nvim-qt.exe is doing anything to set this value that doesn't happen when nvim.exe is called directly?  When I launch nvim.exe I get:

```
Nvim headless-mode started.
Listening on:
        \\.\pipe\nvim-11216-0
Press CTRL+C to exit.
```

So I don't know how to see what's set in there - is there any way I can tell?

**Comment by am2605** [comment]
From nvim/runtime/doc/starting.txt:

> If Vim was started with "-u filename", the file "filename" is used.
> 	All following initializations until 4. are skipped. $MYVIMRC is not
> 	set.

Is this perhaps relevant?

**Comment by am2605** [comment]
Yes, it's definitely to do with the above.

If I change  `"oni.useDefaultConfig": false`, the file now loads.   

So I think because when useDefaultConfig is true, oni passes through the '-u' argument to nvim, I think is actually perfectly correct?

I have found another issue when I useDefaultConfig: false, but I'll open a new issue for that.  I think this one might be okay to close?

**Comment by extr0py** [comment]
Oh, nice find! This explains the behavior I'm seeing now. On my Windows box, I have `oni.loadInitVim` set to `true` - whereas my Linux box I don't have it set. This explains why it works correctly on Windows, but not Linux for me. Thanks for the investigation - glad we know what is going on now! :smile:

Yes, based on the snippet from the docs you posted, it seems this would be expected behavior.

However, I think there are potentially ways we could streamline this experience to make this more intuitive and simpler for the user. Here's a couple of ideas off the top of my head:

## Option 1: Don't use $MYVIMRC variable

For this option, we could resolve the $MYVIMRC path outside of Neovim. We could just open up the one in $XDG_CONFIG_HOME/nvim/init.vim, we'd just need to setup the cross-platform way to get that folder.

Then, when the _Open Neovim Config_ option is selected in the menu, we'd check and see if the `oni.loadInitVim` option is set. If it isn't, we could pop up some UI letting the user know they need to make this change for their `init.vim` to load.

## Option 2: Don't show the _Open Neovim Config_ option unless `oni.loadInitVim` is true or `oni.useDefaultConfig` is false.

For this option - I'm thinking we'd basically hide the _Open Neovim Config_ option unless the user has opted into loading the init vim by setting either of the above config options. I'm gearing Oni towards web developers so my preference is to steer them towards the javascript config (and expose more and more options from there), and only to expose the `init.vim` concept for more advanced Vim users. In this way, the complexity of having two modes of configuration would be hidden, unless a user has specifically opted-in to loading their `init.vim`.

**Comment by keforbes** [comment]
Good job @am2605!

@extr0py, I like your idea with Option 2, especially if it's more aligned with your vision for the project.  I think we should hide `Open Neovim Config` if `oni.loadInitVim` is `false` but I also think we should add a comment in the default `config.js` file which says something along the lines of 
```
"oni.loadInitVim": false #enabling this feature will enable 'Open Neovim Config' menu option
```
So users will know why the menu item may or may not appear.

**Comment by extr0py** [comment]
Looks like this has been fully addressed by @keforbes fix - feel free to open a new issue if there is additional work we should look at here!

**Comment by djwashburn** [comment]
I am still having this problem - I cannot figure out how to get oni to use my .vimrc/init.vim on Windows. I have tried copying it as init.vim AND as the literal filename $VIMRC into ~/.oni/, as well as to C:\Program Files (x86)\Oni, which is where Oni.exe lives and where the default installer put it. I have oni.loadInitVim set to true and have tried with oni.useDefaultConfig set to both true and false. Nothing works. When I click "Edit Neovim Config", it tries to edit C:\Program Files (x86)\Oni\$VIMRC, where $VIMRC is not evaluated but is a literal filename, but if I put my full .vimrc into that file, it still does not get loaded when oni starts.
